<a href="https://colab.research.google.com/github/Biswadeep27/DataPrimer/blob/release_1_0/DeepLearning/PyTorch/01-pytorch-fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals 

In [1]:
#introduction
print('hello world!')

hello world!


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

1.12.1+cu113


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



### Introduction to Tensors

#### Creating Tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# value of scalar - int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([5,7])
vector

tensor([5, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor([[5,7],
                      [7,2]])
MATRIX

tensor([[5, 7],
        [7, 2]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensors
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,9,8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 9, 8]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

* Why Random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnet the data.

`Start with random nmbers -> look at data -> update random numbers -> look at data -> update random numbers`