In [1]:
import numpy as np

In [7]:
# vector
u = np.arange(4)
v = np.random.randint(0,9,4)

In [8]:
u

array([0, 1, 2, 3])

In [9]:
v

array([7, 8, 6, 3])

In [10]:
u * v

array([ 0,  8, 12,  9])

### vector vector multiplication

* length of each vecort needs to be same

In [14]:

def vector_vector_multiplicstion(u, v):
    assert u.shape[0] == v.shape[0]

    u_shape = u.shape[0]
    result = 0

    for _idx in range(u_shape):
        result += u[_idx] * v[_idx]

    return result

In [15]:
vector_vector_multiplicstion(u, v)


29

In [16]:
u.dot(v)

29

In [17]:
v.dot(u)

29

### matrix - vector multiplication
* size of matrix - m x n
* size of vector - n
* ouput - vector of size m
* no of cols in matrix must match with the length of the vector

In [18]:
U = np.random.randint(0,10,(3,4))
V = np.random.randint(0,10,(4,3))

In [19]:
U

array([[8, 0, 2, 1],
       [1, 7, 3, 9],
       [1, 3, 8, 2]])

In [20]:
V

array([[3, 8, 2],
       [8, 5, 1],
       [3, 8, 0],
       [4, 5, 8]])

In [31]:

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    iter_len = U.shape[0]
    result = np.zeros(iter_len,dtype=int)

    for idx in range(iter_len):
        result[idx] = vector_vector_multiplicstion(U[idx],v)

    return result


In [28]:
U.shape, v.shape

((3, 4), (4,))

In [32]:
matrix_vector_multiplication(U, v)

array([ 71, 108,  85])

In [25]:
U.dot(v)

array([ 71, 108,  85])

### matrix - matrix multiplication

* matrix U of size (p x q)
* matrix V of size (q x r)
* output - matrix of size (p x r)

In [34]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols), dtype=int)

    for idx in range(num_cols):
        vidx = V[:,idx]
        Uvidx = matrix_vector_multiplication(U, vidx)

        result[:,idx] = Uvidx

    return result

In [35]:
matrix_matrix_multiplication(U,V)

array([[ 34,  85,  24],
       [104, 112,  81],
       [ 59,  97,  21]])

In [36]:
U.dot(V)

array([[ 34,  85,  24],
       [104, 112,  81],
       [ 59,  97,  21]])

In [37]:
v_mat = v.reshape(4,1)
v_mat

array([[7],
       [8],
       [6],
       [3]])

In [38]:
U

array([[8, 0, 2, 1],
       [1, 7, 3, 9],
       [1, 3, 8, 2]])

In [39]:
U.dot(v_mat)

array([[ 71],
       [108],
       [ 85]])

### Identity Matrix
* U.I = U
* I.U = U

In [40]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
U.shape

(3, 4)

In [42]:
I = np.eye(4,dtype=int)

In [44]:
U.dot(I)

array([[8, 0, 2, 1],
       [1, 7, 3, 9],
       [1, 3, 8, 2]])

### Inverse of square matrix
* $A^{-1}.A = I$

In [45]:
V.shape

(4, 3)

In [47]:
V[:3,:]

array([[3, 8, 2],
       [8, 5, 1],
       [3, 8, 0]])

In [48]:
V[[0,1,2]]

array([[3, 8, 2],
       [8, 5, 1],
       [3, 8, 0]])

In [54]:
Vsq = V[[0,1,2]].astype('float64')

Vsq

array([[3., 8., 2.],
       [8., 5., 1.],
       [3., 8., 0.]])

In [55]:
Vsq_inv = np.linalg.inv(Vsq)
Vsq_inv

array([[-8.16326531e-02,  1.63265306e-01, -2.04081633e-02],
       [ 3.06122449e-02, -6.12244898e-02,  1.32653061e-01],
       [ 5.00000000e-01,  2.08166817e-17, -5.00000000e-01]])

In [56]:
Vsq.dot(Vsq_inv)

array([[ 1.00000000e+00,  4.16333634e-17,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [52]:
Vsq_inv.dot(Vsq)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 5.55111512e-17,  1.00000000e+00, -6.93889390e-18],
       [-1.11022302e-16, -8.88178420e-16,  1.00000000e+00]])