In [1]:
import numpy as np

np.__version__

'1.22.3'

### Creating 1D numpy arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.array([1,2,3,9],dtype=int)

array([1, 2, 3, 9])

In [9]:
np.full(5,27)

array([27, 27, 27, 27, 27])

In [10]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Creating Multi-dimentional Array

In [19]:
np.zeros((5,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
np.array([[1,2,3],[4,5,6,7]],dtype=object)

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [16]:
np.array([[2,1],[5,1],[4,7]])

array([[2, 1],
       [5, 1],
       [4, 7]])

In [20]:
narr = np.array([
    [1,4,7,2],
    [8,5,1,3],
    [6,8,9,0],
])

In [22]:
narr[1,:3]

array([8, 5, 1])

In [25]:
narr[:,2] = [3,4,5]

In [26]:
narr

array([[1, 4, 3, 2],
       [8, 5, 4, 3],
       [6, 8, 5, 0]])

### random arrays

In [29]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
np.random.seed(2)
np.random.randn(5,2) #random normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [3]:
np.random.seed(2)
a_rand = np.random.randint(low=0, high=50, size=(3,2))
a_rand

array([[40, 15],
       [45,  8],
       [22, 43]])

In [4]:
a_rand[:2,:]

array([[40, 15],
       [45,  8]])

In [5]:
a_rand[[0,1]]

array([[40, 15],
       [45,  8]])

In [31]:
a = np.arange(2,10,2)

In [32]:
a

array([2, 4, 6, 8])

### element wise operation

In [34]:
b = (a + 1) ** 2

In [36]:
b - a 

array([ 7, 21, 43, 73])

### comparison -  element-wise

In [37]:
a

array([2, 4, 6, 8])

In [38]:
a >= 6

array([False, False,  True,  True])

In [40]:
b[1] = 2
b

array([ 9,  2, 49, 81])

In [41]:
a > b

array([False,  True, False, False])

In [43]:
a[a<b]

array([2, 6, 8])

### summerizing operation

In [44]:
a

array([2, 4, 6, 8])

In [45]:
a.max()

8

In [46]:
a.std()

2.23606797749979

In [47]:
a.sum()

20

In [48]:
a.shape

(4,)

In [51]:
new = a.reshape(1,4)
new

array([[2, 4, 6, 8]])

In [52]:
a.size

4

In [53]:
new.size

4

In [54]:
new.shape

(1, 4)